<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="#all">

<xsl:template match="root[@service = 'hello']" mode="title">Minimal Berlioz Sample &#8212; Hello</xsl:template>

<xsl:template match="root[@service = 'hello']" mode="body">
  <h1>Minimal Berlioz Sample</h1>
  <p>
    <xsl:value-of select="content/hello/message"/>
  </p>
  <p>
    This page was generated by <code>HelloGenerator</code>, wrapped by Berlioz,
    and transformed with <code>/WEB-INF/xslt/html/default/hello.xsl</code>.
  </p>
  <p>
    Try <a href="/hello.src">source XML</a>, <a href="/hello.xml">XML</a>,
    or <a href="/hello.json">JSON</a>.
  </p>
  <p>
    &#8592; Back to the <a href="/">welcome page</a>.
  </p>
</xsl:template>

</xsl:stylesheet>
