[versions]
cyclonedx = "3.2.4"
gson = "2.10.1"
jackson = "2.15.3"
jakarta-json = "2.1.3"
javax-json = "1.1.4"
jdt-annotations = "2.2.700"
junit = "4.13.2"
parsson = "1.1.5"
servlet-api = "4.0.1"
slf4j = "2.0.9"
xmlwriter = "1.0.4"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jakarta-json-api = { module = "jakarta.json:jakarta.json-api", version.ref = "jakarta-json" }
javax-json-api = { module = "javax.json:javax.json-api", version.ref = "javax-json" }
jdt-annotations = { module = "org.eclipse.jdt:org.eclipse.jdt.annotation", version.ref = "jdt-annotations" }
junit = { module = "junit:junit", version.ref = "junit" }
parsson = { module = "org.eclipse.parsson:parsson", version.ref = "parsson" }
glassfish-javax-json = { module = "org.glassfish:javax.json", version.ref = "javax-json" }
glassfish-jakarta-json = { module = "org.glassfish:jakarta.json", version = "2.0.1" }
servlet-api = { module = "javax.servlet:javax.servlet-api", version.ref = "servlet-api" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }
xmlwriter = { module = "org.pageseeder.xmlwriter:pso-xmlwriter", version.ref = "xmlwriter" }

[plugins]
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
jreleaser = { id = "org.jreleaser", version = "1.21.0" }
versions = { id = "com.github.ben-manes.versions", version = "0.49.0" }
