/*
 * Copyright 2015 Allette Systems (Australia)
 * http://www.allette.com.au
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pageseeder.berlioz.servlet;

import org.pageseeder.berlioz.xml.Xml;

import java.nio.charset.StandardCharsets;
import java.util.Objects;

/**
 * Holds the results of a transformation process.
 *
 * <p>This class holds information about a process such as its content, processing time (in ms),
 * status, and exception.
 *
 * @author Christophe Lauret
 *
 * @version 0.13.5
 * @since 0.6
 */
public final class XmlContent implements BerliozOutput {

  /**
   * The content generated by the process.
   */
  private final CharSequence content;

  /**
   * The media type for this content.
   */
  private final String mediaType;

  /**
   * Creates some new XML content with the default {@code application/xml} media type.
   *
   * @param content The content.
   */
  public XmlContent(CharSequence content) {
    this.content = content;
    this.mediaType = "application/xml";
  }

  /**
   * Creates content with a specific media type.
   *
   * @param content   The content.
   * @param mediaType The media type (e.g. {@code "application/problem+xml"}, {@code "text/html"}).
   */
  XmlContent(CharSequence content, String mediaType) {
    Objects.requireNonNull(mediaType);
    if (!Xml.isXmlMediaType(mediaType))
      throw new IllegalArgumentException("Invalid media type: " + mediaType);
    this.content = content;
    this.mediaType = mediaType;
  }

  /**
   * @return The actual content.
   */
  @Override
  public CharSequence content() {
    return this.content;
  }

  /**
   * @return The media type for this content.
   */
  @Override
  public String getMediaType() {
    return this.mediaType;
  }

  /**
   * @return Always <code>UTF-8</code>.
   */
  @Override
  public String getEncoding() {
    return StandardCharsets.UTF_8.name();
  }

}
