/*
 * Copyright 2015 Allette Systems (Australia)
 * http://www.allette.com.au
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.pageseeder.berlioz.servlet;

import java.util.Properties;

import javax.xml.transform.Templates;

import org.jspecify.annotations.Nullable;

/**
 * Holds the results of a transformation process.
 *
 * <p>This class holds information about a process such as its content, processing time (in nanoseconds),
 * status and exception.
 *
 * @author Christophe Lauret
 *
 * @version 0.13.0
 * @since 0.7
 */
public final class XSLTransformResult implements BerliozOutput {

  /**
   * The status of a process result.
   *
   * <p>These are loosely based on the HTTP error codes.
   */
  public enum Status {

    /**
     * The process has succeeded.
     */
    OK,

    /**
     * An error has occurred during processing.
     */
    ERROR

  }

  /**
   * The content generated by the process.
   */
  private final CharSequence content;

  /**
   * The processing time in nanoseconds.
   */
  private final long time;

  /**
   * The status of this processing result.
   */
  private final Status status;

  /**
   * Any caught exception.
   */
  private final @Nullable Exception ex;

  /**
   * Any error message.
   */
  private final @Nullable String error;

  /**
   * The content type produced by this transformer.
   */
  private String mediaType = "text/html";

  /**
   * The encoding.
   */
  private String encoding = "utf-8";

  /**
   * Creates a successful transformation result.
   *
   * @param content   The content.
   * @param time      The processing nano seconds.
   * @param templates The templates used for the transformation.
   */
  public XSLTransformResult(CharSequence content, long time, Templates templates) {
    this.content = content;
    this.time = time;
    this.status = Status.OK;
    this.error = null;
    this.ex = null;
    setOutputProperties(templates);
  }

  /**
   * Creates an unsuccessful process result.
   *
   * @param content   The content.
   * @param ex        An exception.
   * @param templates The templates used for the transformation.
   */
  public XSLTransformResult(CharSequence content, Exception ex, @Nullable Templates templates) {
    this.content = content;
    this.time = 0;
    this.status = Status.ERROR;
    this.error = null;
    this.ex = ex;
    if (templates != null) {
      setOutputProperties(templates);
    }
  }

  // ==============================================================================================
  // Immutable fields

  /**
   * @return The transformed content.
   */
  @Override
  public CharSequence content() {
    return this.content;
  }

  /**
   * @return The processing time in nanoseconds.
   */
  public long time() {
    return this.time;
  }

  /**
   * Returns the status of the process result.
   *
   * @return the status of the process result.
   */
  public Status status() {
    return this.status;
  }

  // ==============================================================================================
  // Accessors

  /**
   * @return An error message or <code>null</code> if none.
   */
  public @Nullable String getErrorMessage() {
    return this.error;
  }

  /**
   * @return The exception that occurred, or <code>null</code> if none.
   */
  public @Nullable Exception getException() {
    return this.ex;
  }

  /**
   * @return The content type (MIME) as defined in the XSLT templates.
   */
  @Override
  public String getMediaType() {
    return this.mediaType;
  }

  /**
   * @return The character encoding as defined in the XSLT templates.
   */
  @Override
  public String getEncoding() {
    return this.encoding;
  }

  /**
   * Sets the output properties of this transform result.
   *
   * @see <a href="http://www.w3.org/TR/xslt20/#element-output">XSLT 2.0
   *
   * @param templates the templates used to generate this.
   */
  private void setOutputProperties(Templates templates) {
    Properties p = templates.getOutputProperties();
    this.encoding = p.getProperty("encoding", "utf-8");
    this.mediaType = p.getProperty("media-type", "text/html");
  }

}
