<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="#all">

<xsl:output method="html" media-type="text/html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/root">
  <html lang="en">
    <head>
      <meta charset="UTF-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <title>Minimal Berlioz Sample</title>
      <link rel="icon" href="/favicon.svg" type="image/svg+xml"/>
      <link rel="alternate icon" href="/favicon.ico"/>
      <style>
        body {
          margin: 2rem auto;
          max-width: 40rem;
          padding: 0 1.5rem;
          color: #1f2933;
          font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          line-height: 1.5;
        }
        header {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 1.5rem;
        }
        header img {
          width: 2.5rem;
          height: 2.5rem;
        }
        h1 {
          font-size: 1.5rem;
          margin: 0;
        }
        h2 {
          font-size: 1.05rem;
          margin: 2rem 0 0.5rem;
          border-top: 1px solid #e4e7eb;
          padding-top: 1.25rem;
        }
        code, pre {
          background: #edf2f7;
          border-radius: 4px;
        }
        code {
          padding: 0.1rem 0.3rem;
        }
        pre {
          padding: 0.75rem 1rem;
          overflow-x: auto;
        }
        a {
          color: #2b6cb0;
        }
      </style>
    </head>
    <body>
      <xsl:choose>
        <xsl:when test="@service = 'index'">
          <xsl:call-template name="welcome"/>
        </xsl:when>
        <xsl:otherwise>
          <xsl:call-template name="hello"/>
        </xsl:otherwise>
      </xsl:choose>
    </body>
  </html>
</xsl:template>

<xsl:template name="welcome">
  <header>
    <img src="/favicon.svg" alt=""/>
    <h1>Minimal Berlioz Sample</h1>
  </header>
  <p>
    A small WAR application demonstrating the minimum pieces of a Berlioz site: a
    <code>services.xml</code> mapping URLs to generators, one XSLT stylesheet per output format, and
    a couple of generator styles (modern <code>Generator</code>/<code>OutputWriter</code> and the
    legacy <code>ContentGenerator</code>/<code>XMLWriter</code> API).
  </p>

  <h2>Hello service</h2>
  <p>The same <code>HelloGenerator</code> output, rendered through each format servlet:</p>
  <ul>
    <li><a href="/hello.html">/hello.html</a> &#8212; wrapped in XML, transformed to HTML</li>
    <li><a href="/hello.xml">/hello.xml</a> &#8212; wrapped in XML, transformed by <code>xslt/xml/default.xsl</code></li>
    <li><a href="/hello.src">/hello.src</a> &#8212; the raw, untransformed source XML</li>
    <li><a href="/hello.json">/hello.json</a> &#8212; transformed by <code>xslt/json/default.xsl</code></li>
    <li><a href="/hello.html?name=World">/hello.html?name=World</a> &#8212; generator parameter</li>
  </ul>

  <h2>Direct JSON API</h2>
  <p>
    <code>GetNote</code> and <code>UpdateNote</code> are registered with <code>&lt;handler&gt;</code>,
    so they write the response directly instead of going through the XML/XSLT pipeline:
  </p>
  <ul>
    <li><a href="/api/note.json">/api/note.json</a> &#8212; read the current note</li>
  </ul>
  <pre>curl -X POST 'http://localhost:8999/api/note.json?text=Hello%20Berlioz'
curl http://localhost:8999/api/note.json</pre>

  <h2>Error handling</h2>
  <p><code>ErrorGenerator</code> triggers failures on demand, to exercise the Problem Details pipeline:</p>
  <ul>
    <li><a href="/test/error.html">/test/error.html</a> &#8212; no error requested</li>
    <li><a href="/test/error.html?problem=true">/test/error.html?problem=true</a> &#8212; RFC&#160;9457 problem response</li>
    <li><a href="/test/error.html?throw=true">/test/error.html?throw=true</a> &#8212; uncaught exception</li>
    <li><a href="/test/error.html?http=451">/test/error.html?http=451</a> &#8212; a chosen HTTP status</li>
    <li><a href="/api/error.json?problem=true">/api/error.json?problem=true</a> &#8212; same problem, as a direct JSON handler</li>
  </ul>

  <p>Run over HTTPS on <a href="https://localhost:8444/hello.html">https://localhost:8444/hello.html</a>.</p>
</xsl:template>

<xsl:template name="hello">
  <h1>Minimal Berlioz Sample</h1>
  <p>
    <xsl:value-of select="//hello/message"/>
  </p>
  <p>
    This page was generated by <code>HelloGenerator</code>, wrapped by Berlioz,
    and transformed with <code>/WEB-INF/xslt/html/default.xsl</code>.
  </p>
  <p>
    Try <a href="/hello.src">source XML</a>, <a href="/hello.xml">XML</a>,
    or <a href="/hello.json">JSON</a>.
  </p>
  <p>
    &#8592; Back to the <a href="/">welcome page</a>.
  </p>
</xsl:template>

</xsl:stylesheet>
