<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="#all">

<xsl:output method="html" media-type="text/html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
  <html lang="en">
    <head>
      <meta charset="UTF-8"/>
      <title>Minimal Berlioz Sample</title>
      <style>
        body {
          margin: 2rem auto;
          max-width: 48rem;
          color: #1f2933;
          font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
          line-height: 1.5;
        }
        code {
          background: #edf2f7;
          border-radius: 4px;
          padding: 0.1rem 0.3rem;
        }
      </style>
    </head>
    <body>
      <h1>Minimal Berlioz Sample</h1>
      <p>
        <xsl:value-of select="//hello/message"/>
      </p>
      <p>
        This page was generated by <code>HelloGenerator</code>, wrapped by Berlioz,
        and transformed with <code>/WEB-INF/xslt/html/default.xsl</code>.
      </p>
      <p>
        Try <a href="/hello.src">source XML</a>, <a href="/hello.xml">XML</a>,
        or <a href="/hello.json">JSON</a>.
      </p>
    </body>
  </html>
</xsl:template>

</xsl:stylesheet>
